bundle:
  groupId: "io.github.linuxsuren"
  artifactId: "jenkins-zh"
  description: "Jenkins with Pipeline suite"
  vendor: "Chinese Jenkins Community"
buildSettings:
  docker:
    base: "jenkins/jenkins:2.223"
    tag: "jenkins-zh/jenkins-pipeline:2.223"
    build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.223
plugins:
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "localization-zh-cn"
    source:
      version: 1.0.13
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.35"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "2.6"
casc:
  - id: "jcasc"
    source:
      dir: casc.yaml
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: cwp-init.groovy
