bundle:
  groupId: "io.github.linuxsuren"
  artifactId: "jenkins-zh"
  description: "Jenkins with Pipeline suite"
  vendor: "Chinese Jenkins Community"
buildSettings:
  docker:
    base: "jenkins/jenkins:{{.version}}"
    tag: "jenkinszh/jenkins-pipeline:{{.version}}"
    build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: {{.version}}
plugins:
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git"
    source:
      version: 4.2.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "matrix-project"
    source:
      version: "1.14"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "apache-httpcomponents-client-4-api"
    source:
      version: "4.5.10-2.0"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "localization-zh-cn"
    source:
      version: 1.0.14
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.35"
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: "2.6"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "script-security"
    source:
      version: 1.71
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "jackson2-api"
    source:
      version: 2.10.3
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials"
    source:
      version: 2.3.3
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: 2.22
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: 1.20
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "cloudbees-folder"
    source:
      version: 6.11
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: 1.30
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      version: 2.40
  # Pipeline: Model API
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-api"
    source:
      version: 1.6.0
  # Pipeline: Declarative
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-definition"
    source:
      version: 1.6.0
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-cps"
    source:
      version: 2.80
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      version: 3.4
  # Pipeline: Declarative Extension Points API
  - groupId: "org.jenkinsci.plugins"
    artifactId: "pipeline-model-extensions"
    source:
      version: 1.6.0
  # Pipeline: Job
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: 2.33
  # Pipeline: Basic Steps
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-basic-steps"
    source:
      version: 2.18
  # Pipeline: Nodes and Processes
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      version: 2.35
  # Pipeline: SCM Step
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-scm-step"
    source:
      version: 2.10
  # SCM API Plugin
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: 2.6.3
  # Pipeline restFul API Plugin
  - groupId: "io.jenkins.plugins"
    artifactId: "pipeline-restful-api"
    source:
      version: 0.11
casc:
  - id: "jcasc"
    source:
      dir: casc.yaml
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: cwp-init.groovy
