name: Build Custom War Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: maven
          restore-keys: maven
      - name: Build & Update
        env:
          VERSION: 2.223
        run: |
          wget https://dl.bintray.com/jenkins-zh/generic/jenkins-cli/dev/jcli-linux-amd64.tar.gz
          tar xzvf jcli-linux-amd64.tar.gz
          export PATH=.:$PATH
          make linux
          docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{secrets.DOCKER_HUB_TOKEN}}
          ./cj build --username ${{ secrets.BINTRAY_USER }} --token ${{ secrets.BINTRAY_TOKEN }}
