name: Sync Jenkins Version

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: maven
          restore-keys: maven
      - name: Build & Update
        run: |
          curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv
          export PATH=.:$PATH
          make linux cj-check
          cat config.yaml
          git fetch --unshallow
          git checkout master
          git config --local user.email "361981269@qq.com"
          git config --local user.name "rick"
          git add config.yaml
          (git status | grep config.yaml) && git commit -m 'Auto commit by rick bot'
          git push https://linuxsuren:${{ secrets.GITHUB_SECRETS }}@github.com/jenkins-zh/jenkins-formulas.git
