name: Sync Jenkins Version

#on:
#  schedule:
#    - cron: "0 16 * * *"
on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Build & Update
        run: |
          wget https://dl.bintray.com/jenkins-zh/generic/jenkins-cli/dev/jcli-linux-amd64.tar.gz
          tar xzvf jcli-linux-amd64.tar.gz
          export PATH=.:$PATH
          which jcli
          make linux cj-check cj-build
